## ingame-debug.yaml
label-debug-panel-title = Cheats
checkbox-debug-panel-instant-build = Instant Build Speed
checkbox-debug-panel-enable-tech = Build Everything
checkbox-debug-panel-build-anywhere = Build Anywhere
checkbox-debug-panel-unlimited-power = Unlimited Power
checkbox-debug-panel-instant-charge = Instant Charge Time
checkbox-debug-panel-disable-visibility-checks = Disable Visibility Checks
button-debug-panel-give-cash = Give $20,000
button-debug-panel-give-cash-all = Give Cash All
button-debug-panel-heal-selected = Heal Selected
button-debug-panel-dispose-selected = Dispose Selected
button-debug-panel-grow-resources = Grow Resources
button-debug-panel-kill-selected = Kill Selected
button-debug-panel-clear-shroud = Clear Shroud
button-debug-panel-reset-shroud = Reset Shroud
button-debug-panel-level-up = Level Up
button-debug-panel-player-experience = Player Experience
label-debug-panel-selection-title = Selection
label-debug-panel-visualizations-title = Visualizations
checkbox-debug-panel-show-unit-paths = Show Unit Paths
checkbox-debug-panel-show-customterrain-overlay = Show Custom Terrain
checkbox-debug-panel-show-actor-tags = Show Actor Tags
checkbox-debug-panel-show-combatoverlay = Show Combat Geometry
checkbox-debug-panel-show-geometry = Show Render Geometry
checkbox-debug-panel-show-terrain-overlay = Show Terrain Geometry
checkbox-debug-panel-show-celltrigger-overlay = Show Cell Triggers
checkbox-debug-panel-show-actormap-overlay = Show Actor Map
checkbox-debug-panel-show-screenmap = Show Screen Map
checkbox-debug-panel-show-hpf-overlay = Show HPF Overlay
label-debug-panel-saveload-title = Save / Load
button-debug-panel-save-snapshot = Save Now
button-debug-panel-capture-diff = Capture State
button-debug-panel-compare-diff = Compare State
label-debug-panel-sync-hash-title = Sync hash:
label-debug-panel-world-tick-title = Tick:
label-debug-panel-save-format-title = Format:
label-debug-panel-save-format-snapshot = Snapshot
label-debug-panel-save-format-replay = Replay (scripted map)
label-debug-panel-diff-not-captured = No state captured yet
label-debug-panel-diff-captured = State captured; compare after loading
label-debug-panel-diff-matches = Matches the captured state
label-debug-panel-diff-differs = { $count } differences; see the log
